filter:
    excluded_paths:
        - "tests/*"
        - "protect_before_launch.module"

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 3600
