filter:
    excluded_paths:
        - "tests/*"
        - "vendor/*"
        - "protect_before_launch.module"

checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 3600

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
